### ISSUE TITLE
prepare a 3h long Continual AI lecture

### ISSUE THREAD

**Issue by emanueledellavalle** [emanueledellavalle/streaming-data-analytics#18]
if I remember correctly, last year we failed to put all we want to teach in 1h30m (net, 2h gross). The RNN parts is now in the TSA lectures, we have 3h for Continual AI.

**Comment by emanueledellavalle** [comment]
The second lecture will be on Avalange

**Comment by federicogiannini13** [comment]
- We now have two blocks of slides for the first lecture. The first introduces CL. The second presents the strategies. I won't enter into the details of the second during the class.
- I also added three notebooks that I will show already run during the second lecture. The first is an introduction to CL with pytorch. The second uses Avalanche in Task Incremental Learning. The third uses Avalanche in a Class Incremental Learning.
