### ISSUE TITLE
Correzione della "position" 

### ISSUE THREAD

**Issue by lucamainini** [emanueledellavalle/streaming-data-analytics#3]
Buongiorno prof, 
Come dicevamo in classe, andrebbe corretta la posizione dei droni che raccolgono dal secondo albero (la posizione dovrebbe essere 'B2').
> DronePicking = {droneID = 2, servicedTreeID = 2, position = 'A1'} 
mentre 
> TreeToPickTomatoesFrom = {treeID = 2 , position = 'B2', type = 'yellow', pick_start = 3, pick_end = 70}

Buona giornata

**Comment by emanueledellavalle** [comment]
grazie, dovremmo aver gestito.
