### ISSUE TITLE
error in MAPE metric

### ISSUE THREAD

**Issue by VladMarianCimpeanu** [emanueledellavalle/streaming-data-analytics#6]
I think there is an error in the implementation of the MAPE metric in the following notebooks:
- [TSA_05_ForecastingMetrics.ipynb](https://github.com/emanueledellavalle/streaming-data-analytics/blob/main/codes/TSA/TSA_05_ForecastingMetrics.ipynb)
- [TSA_06_Forecasting_Sol.ipynb](https://github.com/emanueledellavalle/streaming-data-analytics/blob/main/codes/TSA/TSA_06_Forecasting_Sol.ipynb)

It is defined as:
```
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100 / len(y_true)
```
But I guess it should be (removed the division by the length of *y*):

```
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
```

**Comment by gziffer** [comment]
Yes, you are right! Thank you for the correction, I have updated both notebooks.
