### ISSUE TITLE
introdurre metriche rolling quando si presentano i metodi capaci di gestire concept drift

### ISSUE THREAD

**Issue by emanueledellavalle** [emanueledellavalle/streaming-data-analytics#8]
I notebook su SML sembrano sempre utilizzare una landamark window nel valutare le metriche. Va bene quando non ci sono concept drift, ma in presenza di drift serve usare una finestra sliding. River sembra supportarle con le [rolling metrics](https://riverml.xyz/0.11.1/api/metrics/Rolling/).

**Comment by alessiobernardo** [comment]
Fatto

**Comment by emanueledellavalle** [comment]
ottimo grazie. Poi mi racconti per favore? Hai fatto la stessa modifica anche in quello per le lezioni Quantia?

Ciao,

Emanuele

**Comment by alessiobernardo** [comment]
Si certo per entrambe le cose
